### ISSUE TITLE
Refactorizar el makefile

### ISSUE THREAD

**Issue by BraulioVM** [practicas-mp/tsp-2#3]
El nuevo makefile debería permitir:
- Añadir nuevos algoritmos fácilmente para ser compilados
- Permitir obtener gráficas de cómo se comportan los algoritmos con los mapas

Bonus:
- Comparar los algoritmos entre sí
- Permitir la compilación de los binarios con los algoritmos a partir del único fuente `main.cpp` a través de directivas de preprocesador y [esto](http://stackoverflow.com/questions/2299824/how-do-i-use-c-preprocessor-to-make-a-substitution-with-an-environment-variable)

**Comment by namasme** [comment]
Soy tu hombre
