### ISSUE TITLE
Error con algoritmo de inserción

### ISSUE THREAD

**Issue by BraulioVM** [practicas-mp/tsp-2#5]
Tal como está ahora mismo, el algoritmo de mejor inserción elige como ruta inicial aquella que une las dos primeras ciudades. Sin embargo, el profesor nos dijo que la ruta inicial sería aquella ruta de tres ciudades que forme el mayor triángulo posible. 

@cronos2

**Comment by namasme** [comment]
No, dijo que _podía_ ser la ruta inicial.

**Comment by BraulioVM** [comment]
Ah va va, pues entonces ya está
